### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in 'C:\Dev\client-apps\react-query-builder\node_modules\sql-parser-mistic\lib'

### ISSUE THREAD

**Issue by hu1da** [mistic100/sql-parser#15]
I use it with react-app and I've got an error:

Module not found: Error: Can't resolve 'fs' in '<my path>\node_modules\sql-parser-mistic\lib' .
How can I use it within browser application?

**Comment by mistic100** [comment]
Try to configure your build chain to use `sql-parser-mistic/browser/sql-parser.js`

**Comment by mistic100** [comment]
By the way I don't see any usage of fs in the sources.
