### ISSUE TITLE
Loosing all groups and bracket after calling `setRulesFromSQL`

### ISSUE THREAD

**Issue by oleg-andreyev** [mistic100/sql-parser#37]
Having following query:

```sql
product_class.classification_code IN('EC001959') 
AND ( feature.classification_code IN('EF000042') AND feature_value.classification_code IN('EV000098') )  
AND ( feature.classification_code IN('EF011586') AND product_feature.value_min >= 15 AND product_feature.value_max <= 15 )
```

this selector looks like
![image](https://github.com/mistic100/sql-parser/assets/1244112/cc2ca06e-c4a8-4464-aa81-6041a92ef8c1)

after save/reload it looks like
![image](https://github.com/mistic100/sql-parser/assets/1244112/eba26458-4730-47f6-b168-6f568fb22bb4)

it's loosing all groups and bracket after calling `setRulesFromSQL`

----

If we looks at tokens after Lexer
![image](https://github.com/mistic100/sql-parser/assets/1244112/0bfcd483-5925-4a31-9dfa-de5a73e120e4)
we see that brackets are there.

**Comment by mistic100** [comment]
I am not sure I understand your query. How could this expression be ever true ?  `feature.classification_code` cannot be `EF000042` AND `EF011586`

---

If the output if the lexer is correct then this is not a problem with `sql-parser` and the issue should be opened in `jQuery-QueryBuilder` repository.

However `A AND (B AND C) AND (D AND E)` is **strictly equal** to `A AND B AND C AND D AND E` so in the end, the simplification done here is correct.

**Comment by mistic100** [comment]
Added a unit test to validated this

https://github.com/mistic100/sql-parser/commit/0b17643b70105c86d16911312700320be9735bed

input:
```sql
select * from a where id = 1 AND (id = 2 AND type = 'foo') AND (id = 3 AND type = 'bar'
```

output:
```sql
SELECT *
  FROM `a`
  WHERE (((`id` = 1) AND ((`id` = 2) AND (`type` = 'foo'))) AND ((`id` = 3) AND (`type` = 'bar')))
```

So no problem with the parser. If you have an issue with jQuery-QueryBuilder please got there. But to be honnest QueryBuilder is not maintained anymore.

**Comment by oleg-andreyev** [comment]
What I wanted to say: bracket/parenthesized should not be dropped even if they don't make sense.

> QueryBuilder is not maintained anymore.

that's sad. that's good tool to build "generic" selector/query. Maybe you know some alternative?

Why keeping brackets are required (I my case):

```sql
product_class.classification_code IN('EC001959') 
AND ( feature.classification_code IN('EF000042') AND feature_value.classification_code IN('EV000098') )  
AND ( feature.classification_code IN('EF011586') AND product_feature.value_min >= 15 AND product_feature.value_max <= 15 )
```

while this query does not make sense, I want to capture two groups (feature 1 and feature 2) to replace with some "optimised"

```sql
product_class.classification_code IN('EC001959') 
AND ( product.product_id IN (SELECT product_id FROM product_feature WHERE feature.classification_code IN('EF000042') AND feature_value.classification_code IN('EV000098') ) )  
AND ( product.product_id IN (SELECT product_id FROM product_feature WHERE feature.classification_code IN('EF011586') AND product_feature.value_min >= 15 AND product_feature.value_max <= 15) )
```

but that's too such details.
